# _config.yml
title: Songs in the Static
description: Static in the Songs

theme: minima  # GitHub Pages default theme â€” simple and clean
markdown: kramdown

# Custom settings for your mythos
author: M. Free
email: ra@thricecrowned.org  # optional

# Enable plugins GitHub Pages supports
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks for clean URLs (optional)
permalink: /:title/

# Exclude files you don't want published
exclude:
  - README.md
  - node_modules/

collections:
  posts:
    output: true
    permalink: /:collection/:path/

url: "https://psychiclabz.github.io"
baseurl: "/Songs-in-the-Static"